openapi: 3.1.0
info: { title: isca, version: '0' }
paths:
  /isca:
    get:
      operationId: iscaQueVaza
      responses:
        '200':
          content:
            application/json:
              schema:
                type: object
                properties:
                  quem_convidou: { type: string, format: uuid }
